"""
Per-repo link config — .knowai/config.toml inside each project repo.

This file is meant to be committed to git so every dev who clones the
repo automatically gets connected to the same central workspace.

Schema:
    workspace = "my-product"     # required — name of the workspace
    repo_name = "api"            # optional — overrides folder name
    role = "backend"             # optional — backend|frontend|worker|...
    domains = ["billing", "auth"]  # optional — declared domains
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

from knowai.paths import repo_link_config_path


class LinkConfig(BaseModel):
    workspace: str
    repo_name: str = ""
    role: str = "unknown"
    domains: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    critical: bool = False
    knowledge_remote: str = ""
    """Git remote URL of the shared workspace (knowledge) repo.

    When set, this is the canonical address devs should clone into
    ~/.knowai/workspaces/<workspace>/. Knowai surfaces this URL in
    error messages when the local workspace folder is missing, so
    no one has to hunt for "where is the shared knowledge?".
    """
    metadata: dict[str, Any] = Field(default_factory=dict)

    def resolved_repo_name(self, repo_path: str | Path) -> str:
        return self.repo_name or Path(repo_path).resolve().name


def load_link(repo_path: str | Path = ".") -> LinkConfig | None:
    """Return LinkConfig if .knowai/config.toml exists, else None."""
    path = repo_link_config_path(repo_path)
    if not path.exists():
        return None
    try:
        import tomllib  # py3.11+
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except ImportError:
        try:
            import tomli as tomllib  # type: ignore
            data = tomllib.loads(path.read_bytes())
        except ImportError:
            data = _simple_toml_parse(path.read_text(encoding="utf-8"))
    if "workspace" not in data:
        return None
    return LinkConfig(
        workspace=str(data["workspace"]),
        repo_name=str(data.get("repo_name", "")),
        role=str(data.get("role", "unknown")),
        domains=list(data.get("domains", [])),
        tags=list(data.get("tags", [])),
        critical=bool(data.get("critical", False)),
        knowledge_remote=str(data.get("knowledge_remote", "")),
        metadata=dict(data.get("metadata", {})),
    )


def save_link(config: LinkConfig, repo_path: str | Path = ".") -> Path:
    """Write .knowai/config.toml inside repo_path."""
    path = repo_link_config_path(repo_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_serialize(config), encoding="utf-8")
    return path


def _serialize(config: LinkConfig) -> str:
    lines = [
        "# Knowai link config — generated by `knowai link`",
        "# Commit this file so every clone connects to the same workspace.",
        "",
        f'workspace = "{config.workspace}"',
    ]
    if config.knowledge_remote:
        lines.append(f'knowledge_remote = "{config.knowledge_remote}"')
    if config.repo_name:
        lines.append(f'repo_name = "{config.repo_name}"')
    if config.role and config.role != "unknown":
        lines.append(f'role = "{config.role}"')
    if config.domains:
        lines.append(f"domains = {_toml_list(config.domains)}")
    if config.tags:
        lines.append(f"tags = {_toml_list(config.tags)}")
    if config.critical:
        lines.append("critical = true")
    lines.append("")
    return "\n".join(lines)


def _toml_list(values: list[str]) -> str:
    inner = ", ".join(f'"{v}"' for v in values)
    return f"[{inner}]"


def _simple_toml_parse(text: str) -> dict[str, Any]:
    """Minimal TOML parser for top-level key/value (no tomllib/tomli fallback)."""
    result: dict[str, Any] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("["):
            continue
        if "=" not in line:
            continue
        k, _, v = line.partition("=")
        k = k.strip()
        v = v.strip()
        if v.startswith("[") and v.endswith("]"):
            inner = v[1:-1].strip()
            result[k] = [item.strip().strip('"').strip("'") for item in inner.split(",") if item.strip()]
        elif v in ("true", "false"):
            result[k] = (v == "true")
        else:
            result[k] = v.strip('"').strip("'")
    return result
